services:
  webserver:
    image: nginx:latest
    volumes:
      # Mount local configuration to containers' configuration
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      # Default nginx
      - 80:80
      # PHP app one PORT
      - 81:81
      # PHP app two PORT
      - 82:82
      # Load balancer
      - 8009:8009